version: '3'
services:
  backend:
    build: ./
    ports:
      - "80:80"
      - "443:443"
    environment:
      - FLASK_ENV=dev
    links:
      - db:db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=authnid
      - POSTGRES_USER=atat
      - POSTGRES_PASSWORD=password
