version: '3'
services:
  backend:
    build: ./
    ports:
      - "8001:443"
    environment:
      - FLASK_ENV
    links:
      - db:db
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=authnid
      - POSTGRES_USER=atat
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
