version: '3'
services:
  pgadmin:
    image: fenglc/pgadmin4
    depends_on:
      - db
    environment:
      - DEFAULT_USER=admin@cac.atat.codes
      - DEFAULT_PASSWORD=NXUJHjedjb7CXx[M
  swagger-ui:
    image: swaggerapi/swagger-ui
  proxy:
    image: traefik:v1.5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  flower:
    image: totem/celery-flower-docker
    environment:
      - FLOWER_BASIC_AUTH=root:changethis
