version: '3'
services:
  backend-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
    command: bash -c "while true; do sleep 1; done"
    volumes:
      - './app:/app'
    environment:
      - SERVER_NAME=${DOMAIN}
      - FIRST_SUPERUSER=admin@cac.atat.codes
      - FIRST_SUPERUSER_PASSWORD=cac
  backend:
    command: bash -c "flask run --host=0.0.0.0 --port=80"
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app/main.py
      - VIRTUAL_HOST=${DOMAIN}
    networks:
      default:
        aliases:
          - ${DOMAIN}
