version: '3'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: NXUJHjedjb7CXx[M
      PGDATA: /var/lib/postgresql/data/pgdata
  backend:
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      - VIRTUAL_HOST=${DOMAIN}
      - SECRET_KEY=1faa14e769f5722ab658fe53120301e0623327aff4824471ee13b1aa93e74650
      - SENTRY_DSN=
      - POSTGRES_PASSWORD=NXUJHjedjb7CXx[M
      - FIRST_SUPERUSER=admin@cac.atat.codes
      - FIRST_SUPERUSER_PASSWORD=cac
