version: '3'
services:
  db:
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: fenglc/pgadmin4
    depends_on:
      - db
    environment:
      - DEFAULT_USER=admin@cac.atat.codes
      - DEFAULT_PASSWORD=NXUJHjedjb7CXx[M
    ports:
      - '5050:5050'
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=https://${DOMAIN}/api/v1/swagger/
    ports:
      - '8080:8080'
  backend:
    build:
      context: ./
      args:
        env: dev
    networks:
      default:
        aliases:
          - ${DOMAIN}
    volumes:
      - './app:/app'
    environment:
      - FLASK_APP=app/main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    # command: bash -c "while true; do sleep 1; done"
    # command: bash -c "flask run --host=0.0.0.0 --port=80"
  backend-tests:
    build:
      context: .
      dockerfile: Dockerfile-tests
      args:
        env: dev
    environment:
      - SERVER_NAME=backend
      - FIRST_SUPERUSER=admin@cac.atat.codes
      - FIRST_SUPERUSER_PASSWORD=cac
      # this sets the CA for the test requests
      - REQUESTS_CA_BUNDLE=/etc/ssl/ca.crt
      # - SEED=0
    command: bash -c "while true; do sleep 1; done"
    volumes:
      - ./app:/app
      - ./ssl:/etc/ssl
    ports:
      - '8888:8888'

volumes:
  app-db-data:
