"""a revision

Revision ID: dc3f3f4d2ddd
Revises: f121d6df64c6
Create Date: 2018-05-30 17:15:28.955009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3f3f4d2ddd'
down_revision = 'f121d6df64c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
