#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

set -e
cd "$(dirname "$0")/.."

# Install Python dependencies
pipenv install --dev

# build docker container
docker-compose build
docker-compose run backend pipenv run alembic upgrade head
