#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."

rm -rf crl ALLCRLZIP.zip || true
mkdir -p crl

# wget -O ALLCRLZIP.zip --ca-certificate=./ssl/server-certs/ca-chain.pem https://crl.gds.disa.mil/getcrlzip?ALL+CRL+ZIP
# wget http://e80941f84921e909ab16-e354358e56dcbb7455ea93938bd936fa.r78.cf5.rackcdn.com/ALLCRLZIP.zip
# unzip -o ALLCRLZIP.zip -d crl/
# find crl -type f | grep -Ev "crl/DOD(ROOT|ID|EMAIL)" | xargs rm

# just include our dummy CRL for now
cp ssl/client-certs/client-ca.der.crl crl/

# Install pipenv
if [ -n "$CI" ]; then
  pip install pipenv
else
  pip install -q pipenv --user
fi

script/down
script/bootstrap
