#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."

mkdir -p crl

if [ ! -e ALLCRLZIP.zip ]; then
  # wget -O ALLCRLZIP.zip --ca-certificate=./ssl/server-certs/ca-chain.pem https://crl.gds.disa.mil/getcrlzip?ALL+CRL+ZIP
  wget http://e80941f84921e909ab16-e354358e56dcbb7455ea93938bd936fa.r78.cf5.rackcdn.com/ALLCRLZIP.zip
  unzip -o ALLCRLZIP.zip -d crl/
fi

cp ssl/client-certs/client-ca.der.crl crl/

script/down
script/bootstrap

