#!/bin/bash

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e
cd "$(dirname "$0")/.."

# include our dummy CRL for now
cp ssl/client-certs/client-ca.der.crl crl/

# Install pipenv
if [ -n "$CI" ]; then
  pip install pipenv
else
  pip install -q pipenv --user
fi

script/down
script/bootstrap
