#!/bin/bash

# script/sync-crls: update the DOD CRLs and place them where authnid expects them

rm -rf crl/ || true
mkdir -p crl
echo "Updating local CRLs..."
pipenv run python ./authnid/crl/util.py crl

if [[ $FLASK_ENV != "production" ]]; then
  # place our test CRL there
  cp ssl/client-certs/client-ca.der.crl crl/
fi
