#!/bin/bash

# script/server: Launch the application and any extra required processes
#                locally.

set -e
cd "$(dirname "$0")/.."

# ensure everything in the app is up to date.
script/update
# bring up the application stack
script/up

#TODO wait for application to become responsive

echo "==> Running tests…"

# if [ -n "$1" ]; then
  # pass arguments to test call. This is useful for calling a single test.
  # bin/rake test "$1"
# else
  docker-compose run backend-tests pytest $1
# fi
