#!/bin/bash

# script/server: Launch the application and any extra required processes
#                locally.

set -e
cd "$(dirname "$0")/.."

# bring up the application stack
script/up -d

#TODO wait for application to become responsive

echo "==> Running tests…"

FLASK_ENV=test SERVER_NAME=localhost:8001 pipenv run pytest $*
